version: '3'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: edithing
      MYSQL_USER: edithing
      MYSQL_PASSWORD: secret-string
    ports:
      - "3306:3306"

  test_database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: edithing
      MYSQL_USER: edithing
      MYSQL_PASSWORD: secret-string
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15672"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery
