# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests and build 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run tests and build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: edithing
      DATABASE_USER: edithing
      DATABASE_PASSWORD: secret-string

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile


    - name: Prepare git to be executed by the app
      run: |
        git --version
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
        git status
        git config --global --add safe.directory ${{ github.workspace }}

    - name: Build all packages
      run: pnpm -r build

    - run: pnpm run lint
    - run: pnpm run typecheck

    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'edithing'
        mysql user: "edithing"
        mysql password: "secret-string"
        host port: 3307
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
    
    - name: Run tests
      run: pnpm run test
      env:
        DATABASE_PORT: 3307
        DATABASE_USER: "edithing"
        DATABASE_NAME: "edithing"
